name: Cerberos - Changelog

on:
  # Run on push to Master (should not happen).
  push:
    branches:
      - master

    # Run when any tag is created.
    tags:
      - '*'

  pull_request:
    types:
      - closed

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    name: Generate Changelog

    steps:
      - uses: actions/checkout@v1

      - name: Generate Changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changelog
        env:
          CI_USER: ${{ secrets.CERBEROS_USER }}
          CI_EMAIL: ${{ secrets.CERBEROS_EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      - name: Push Changelog
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.CERBEROS_USER }}
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
